-- MySQL Script generated by MySQL Workbench
-- Thu Sep  3 15:37:13 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bigtrue
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bigtrue
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bigtrue` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `bigtrue` ;

-- -----------------------------------------------------
-- Table `bigtrue`.`yh_member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bigtrue`.`yh_member` (
  `no` INT NOT NULL COMMENT '',
  `mb_id` VARCHAR(32) NULL COMMENT '',
  `mb_pw` VARCHAR(32) NULL COMMENT '',
  `mb_name` VARCHAR(32) NULL COMMENT '',
  `mb_block` INT NULL DEFAULT 0 COMMENT '',
  `mb_group` VARCHAR(255) NULL COMMENT '',
  `mb_loginTime` DATETIME NULL COMMENT '',
  `mb_joinTime` DATETIME NULL COMMENT '',
  `mb_quiz_question` VARCHAR(32) NULL COMMENT '',
  `mb_quiz_answer` VARCHAR(32) NULL COMMENT '',
  `mb_address` VARCHAR(255) NULL COMMENT '',
  `mb_phoneNumber` VARCHAR(32) NULL COMMENT '',
  `mb_telNumber` VARCHAR(32) NULL COMMENT '',
  `mb_email` VARCHAR(45) NULL COMMENT '',
  `mb_emailAccept` INT NULL COMMENT '',
  PRIMARY KEY (`no`)  COMMENT '')



-- -----------------------------------------------------
-- Table `bigtrue`.`yh_quiz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bigtrue`.`yh_quiz` (
  `no` INT NOT NULL COMMENT '',
  `quiz_content` VARCHAR(45) NULL COMMENT '',
  `yh_quizcol` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`no`)  COMMENT '')



-- -----------------------------------------------------
-- Table `bigtrue`.`yh_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bigtrue`.`yh_product` (
  `pd_no` INT NOT NULL COMMENT '',
  `pd_name` VARCHAR(45) NULL COMMENT '',
  `pd_shortDesc` VARCHAR(255) NULL COMMENT '',
  `pd_code` VARCHAR(45) NULL COMMENT '',
  `pd_price` INT NULL COMMENT '',
  `pd_viewCount` INT NULL COMMENT '',
  `pd_regDate` DATETIME NULL COMMENT '',
  `pd_thumbnail` VARCHAR(255) NULL COMMENT '',
  `pd_isProduct` INT NULL COMMENT '',
  PRIMARY KEY (`pd_no`)  COMMENT '')



-- -----------------------------------------------------
-- Table `bigtrue`.`yh_product_sub`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bigtrue`.`yh_product_sub` (
  `no` INT NOT NULL COMMENT '',
  `pd_no` INT NULL COMMENT '',
  `pds_contents` VARCHAR(2500) NULL COMMENT '',
  PRIMARY KEY (`no`)  COMMENT '',
  INDEX `pd_no_idx` (`pd_no` ASC)  COMMENT '',
  CONSTRAINT `pd_no`
    FOREIGN KEY (`pd_no`)
    REFERENCES `bigtrue`.`yh_product` (`pd_no`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)



-- -----------------------------------------------------
-- Table `bigtrue`.`yh_reply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bigtrue`.`yh_reply` (
  `no` INT NOT NULL COMMENT '',
  `pd_no` INT NULL COMMENT '',
  `rp_regDate` DATETIME NULL COMMENT '',
  `rp_content` VARCHAR(255) NULL COMMENT '',
  `mb_no` INT NULL COMMENT '',
  PRIMARY KEY (`no`)  COMMENT '',
  INDEX `pd_no_idx` (`pd_no` ASC)  COMMENT '',
  INDEX `mb_no_idx` (`mb_no` ASC)  COMMENT '',
  CONSTRAINT `pd_no`
    FOREIGN KEY (`pd_no`)
    REFERENCES `bigtrue`.`yh_product` (`pd_no`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `mb_no`
    FOREIGN KEY (`mb_no`)
    REFERENCES `bigtrue`.`yh_member` (`no`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)



-- -----------------------------------------------------
-- Table `bigtrue`.`yh_product_date_option`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bigtrue`.`yh_product_date_option` (
  `no` INT NOT NULL COMMENT '',
  `pd_no` INT NULL COMMENT '',
  `pddo_date` DATETIME NULL COMMENT '',
  PRIMARY KEY (`no`)  COMMENT '',
  INDEX `pd_no_idx` (`pd_no` ASC)  COMMENT '',
  CONSTRAINT `pd_no`
    FOREIGN KEY (`pd_no`)
    REFERENCES `bigtrue`.`yh_product` (`pd_no`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)



-- -----------------------------------------------------
-- Table `bigtrue`.`yh_product_option`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bigtrue`.`yh_product_option` (
  `no` INT NOT NULL COMMENT '',
  `pd_no` INT NULL COMMENT '',
  `pdo_title` VARCHAR(32) NULL COMMENT '',
  `pdo_content` VARCHAR(45) NULL COMMENT '',
  `pdo_additionalPrice` INT NULL COMMENT '',
  PRIMARY KEY (`no`)  COMMENT '',
  INDEX `pd_no_idx` (`pd_no` ASC)  COMMENT '',
  CONSTRAINT `pd_no`
    FOREIGN KEY (`pd_no`)
    REFERENCES `bigtrue`.`yh_product` (`pd_no`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)



-- -----------------------------------------------------
-- Table `bigtrue`.`yh_wishlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bigtrue`.`yh_wishlist` (
  `no` INT NOT NULL COMMENT '',
  `mb_no` INT NULL COMMENT '',
  `pd_no` INT NULL COMMENT '',
  PRIMARY KEY (`no`)  COMMENT '',
  INDEX `mb_no_idx` (`mb_no` ASC)  COMMENT '',
  INDEX `pd_no_idx` (`pd_no` ASC)  COMMENT '',
  CONSTRAINT `mb_no`
    FOREIGN KEY (`mb_no`)
    REFERENCES `bigtrue`.`yh_member` (`no`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `pd_no`
    FOREIGN KEY (`pd_no`)
    REFERENCES `bigtrue`.`yh_product` (`pd_no`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)



-- -----------------------------------------------------
-- Table `bigtrue`.`yh_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bigtrue`.`yh_order` (
  `no` INT NOT NULL COMMENT '',
  `mb_no` INT NULL COMMENT '',
  `pd_no` INT NULL COMMENT '',
  `ord_regDate` DATETIME NULL COMMENT '',
  `ord_amount` INT NULL COMMENT '',
  `ord_totalPrice` INT NULL COMMENT '',
  PRIMARY KEY (`no`)  COMMENT '',
  INDEX `mb_no_idx` (`mb_no` ASC)  COMMENT '',
  INDEX `pd_no_idx` (`pd_no` ASC)  COMMENT '',
  CONSTRAINT `mb_no`
    FOREIGN KEY (`mb_no`)
    REFERENCES `bigtrue`.`yh_member` (`no`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `pd_no`
    FOREIGN KEY (`pd_no`)
    REFERENCES `bigtrue`.`yh_product` (`pd_no`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)



-- -----------------------------------------------------
-- Table `bigtrue`.`yh_product_photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bigtrue`.`yh_product_photo` (
  `no` INT NOT NULL COMMENT '',
  `pd_no` INT NULL COMMENT '',
  `pdp_path` VARCHAR(255) NULL COMMENT '',
  PRIMARY KEY (`no`)  COMMENT '',
  INDEX `pd_no_idx` (`pd_no` ASC)  COMMENT '',
  CONSTRAINT `pd_no`
    FOREIGN KEY (`pd_no`)
    REFERENCES `bigtrue`.`yh_product` (`pd_no`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
